### ISSUE TITLE
Refactor GovKit:SearchEngines::GoogleNews

### ISSUE THREAD

**Issue by jpmckinney** [opengovernment/govkit#1]
Either switch to "output=rss" or "output=atom" or use the JSON API http://code.google.com/apis/newssearch/v1/jsondevguide.html

If we use JSON, then we may be able to make GoogleNewsSearch a descendant of GovKit::Resource (using HTTParty).

For international support, allow configuration of the `ned` parameter.

**Comment by tashian** [comment]
We're now doing RSS, thanks to a patch by @NateBarnes
