### ISSUE TITLE
Add support for OpenGovernment API

### ISSUE THREAD

**Issue by tashian** [opengovernment/govkit#14]
Basic API docs are here:
http://opengovernment.org/pages/api

I think the most interesting / unique API calls here might be:
- Legislator lookup by location (federal AND state)
- Most popular bills & people (by # of views or by news coverage)
- News coverage on bills & people

**Comment by matthewbauer** [comment]
Does this API have the same structure as the Open Congress one?

**Comment by jpmckinney** [comment]
If there is demand for an API wrapper, we can re-open this issue. The OG API is quite simple, so most people will probably be fine using the JSON directly.
