### ISSUE TITLE
Add Support for OpenSecrets.org

### ISSUE THREAD

**Issue by matthewbauer** [opengovernment/govkit#17]
[OpenSecrets.org](http://www.opensecrets.org/) aggregates information on lobbying, financing, and elections.

The administrators provide a [RESTful API](http://www.opensecrets.org/resources/create/apis.php) which from what I can tell could be incorporated into govkit.

**Comment by jpmckinney** [comment]
We accept pull requests, but otherwise are not adding features unless we need them.
