### ISSUE TITLE
VERSION error

### ISSUE THREAD

**Issue by docunext** [opengovernment/govkit#18]
FYI: 

rails generate govkit
/usr/local/rvm/gems/ruby-1.9.2-p180/gems/govkit-0.6.1/lib/gov_kit.rb:13:in `<top (required)>': uninitialized constant VERSION (NameError)
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/govkit-0.6.1/lib/govkit.rb:1:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.17/lib/bundler/runtime.rb:68:in `require'
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.17/lib/bundler/runtime.rb:68:in`block (2 levels) in require'
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.17/lib/bundler/runtime.rb:66:in `each'
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.17/lib/bundler/runtime.rb:66:in`block in require'
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.17/lib/bundler/runtime.rb:55:in `each'
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.17/lib/bundler/runtime.rb:55:in`require'
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.17/lib/bundler.rb:120:in `require'
        from /home/albertlash/savonix/operations/dev/www.2012-presidential-election.info/config/application.rb:7:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/commands.rb:21:in `require'
        from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/commands.rb:21:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'

**Comment by docunext** [comment]
If I comment out:

 13 #if VERSION[0,3] == "1.8"
 14 #  require 'fastercsv'
 15 #end

It works fine.

**Comment by NateBarnes** [comment]
Looks like the static variable VERSION was deprecated in 1.9 in favor of RUBY_VERSION, which works in both. Should be an easy fix.

**Comment by NateBarnes** [comment]
Actually Tashian fixed this back in May. You should update your copy of govkit to the current one and that should fix this issue.

**Comment by docunext** [comment]
Thanks Nate - I installed the gem, has a new gem been published/

**Comment by NateBarnes** [comment]
Versions 0.7.0 and later should have the appropriate fix. It was published on June 28 of this year. You can check your version within your gem list.

If there's anything else I can help with, let me know :)

**Comment by docunext** [comment]
Thanks again, the gem is great, by the way. Ah - I see what the problem is. GovKit 0.7.1 requires activesupport = 3.0.0, I'm using 3.1.0. Hmmm..... I'll try HEAD with AS 3.1.0 and let you know what happens.

**Comment by docunext** [comment]
Oddly, I can't find where the requirement is coming from... found it. Looks like active_support is now activesupport. Its working for me. I'll create pull request as I made a few other changes which you might like.
