### ISSUE TITLE
Cannot install govkit gem

### ISSUE THREAD

**Issue by browning** [opengovernment/govkit#23]
```
Fetching: govkit-0.7.2.gem (100%)
ERROR:  Error installing govkit:
    govkit requires govkit (>= 0)
```

I think you just need to remove the line from the gemspec that makes govkit a dependency:

```
s.add_dependency(%q<govkit>, [">= 0"])
```

**Comment by NateBarnes** [comment]
You are correct. Looks like when the gemspec was rebuilt after moving to 0.7.2, it was added back in (it had been removed previously). I've removed the offending lines and committed the changes. You can install it by building the gem yourself until they push it to rubygems.

Thanks for the tip! Sorry it took so long to get to it :)
