### ISSUE TITLE
Add iconv gem dependency

### ISSUE THREAD

**Issue by jarrodj** [opengovernment/govkit#34]
After installing and adding govkit to my rails project Gemfile, I was unable to run "rails generate" because gov_kit.rb requires iconv.  I got it working after installing iconv and adding it to my rails project Gemfile.

Should iconv be added to the govkit Gemfile?

**Comment by jarrodj** [comment]
I now see that iconv is part of the Ruby standard library. For some reason rvm didn't install it for me.

I don't think there is an issue now.  Sorry, Ruby noob here!

**Comment by NateBarnes** [comment]
It's not a problem at all, thanks for the attempt :)
